//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package org.jug.montpellier.jugdroid.ui;

import android.os.Bundle;
import android.view.View;
import android.view.View.OnClickListener;
import org.jug.montpellier.jugdroid.R.id;

public class DashboardActivity_
    extends DashboardActivity
{


    private void beforeSetContentView_(Bundle savedInstanceState) {
        onBeforeCreate();
    }

    private void afterSetContentView_(Bundle savedInstanceState) {
        partners = ((NewInfoButton) findViewById(id.home_btn_partners));
        news = ((NewInfoButton) findViewById(id.home_btn_news));
        sessions = ((NewInfoButton) findViewById(id.home_btn_sessions));
        about = ((NewInfoButton) findViewById(id.home_btn_about));
        schedule = ((NewInfoButton) findViewById(id.home_btn_schedule));
        members = ((NewInfoButton) findViewById(id.home_btn_members));
        findViewById(id.home_btn_news).setOnClickListener(new OnClickListener() {


            public void onClick(View view) {
                newsClicked();
            }

        }
        );
        findViewById(id.home_btn_about).setOnClickListener(new OnClickListener() {


            public void onClick(View view) {
                aboutClicked();
            }

        }
        );
        findViewById(id.home_btn_members).setOnClickListener(new OnClickListener() {


            public void onClick(View view) {
                membersClicked();
            }

        }
        );
        findViewById(id.home_btn_schedule).setOnClickListener(new OnClickListener() {


            public void onClick(View view) {
                scheduleClicked();
            }

        }
        );
        findViewById(id.home_btn_partners).setOnClickListener(new OnClickListener() {


            public void onClick(View view) {
                partnersClicked();
            }

        }
        );
        findViewById(id.home_btn_sessions).setOnClickListener(new OnClickListener() {


            public void onClick(View view) {
                sessionsClicked();
            }

        }
        );
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        beforeSetContentView_(savedInstanceState);
        afterSetContentView_(savedInstanceState);
        super.onCreate(savedInstanceState);
    }

}
